// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLpUDHtUh4Ap_MvurugtoB1mLnx-l76es',
    appId: '1:62654749324:android:282a6f1d8c418e4925f9a9',
    messagingSenderId: '62654749324',
    projectId: 'bookstore-4fc64',
    storageBucket: 'bookstore-4fc64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnXMyIaCNFJgvCttzANGADLqjrXYG__KM',
    appId: '1:685859908526:ios:4e7c8545ed834d98f0f63f',
    messagingSenderId: '685859908526',
    projectId: 'bookstore-2dc8b',
    storageBucket: 'bookstore-2dc8b.firebasestorage.app',
    iosBundleId: 'com.example.ct484Project',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyKRahdjnzLhn5ZUtdiNXw5XEzgiH-dA',
    appId: '1:62654749324:web:38abc62a3370da9a25f9a9',
    messagingSenderId: '62654749324',
    projectId: 'bookstore-4fc64',
    authDomain: 'bookstore-4fc64.firebaseapp.com',
    storageBucket: 'bookstore-4fc64.firebasestorage.app',
    measurementId: 'G-031153VPJ1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyKRahdjnzLhn5ZUtdiNXw5XEzgiH-dA',
    appId: '1:62654749324:web:c2b0a5469d0dd93725f9a9',
    messagingSenderId: '62654749324',
    projectId: 'bookstore-4fc64',
    authDomain: 'bookstore-4fc64.firebaseapp.com',
    storageBucket: 'bookstore-4fc64.firebasestorage.app',
    measurementId: 'G-6SXXF0R2XM',
  );

}